import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'firebase_options.dart';

import 'app_colors.dart';
import 'main_nav_page.dart';
import 'notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the config generated by `flutterfire configure`.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register background/terminated handler for incoming FCM messages.
  // (Defined as a top-level function inside notification_service.dart —
  // must be registered before runApp, same as before.)
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Everything else — local notification channel setup, asking for the
  // OS Allow/Block permission popup, saving the FCM token to the backend,
  // and the foreground push listener — now lives in ONE place:
  // NotificationService. main.dart no longer duplicates any of that.
  await NotificationService.instance.init();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sumathi\'s Styles',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: AppColors.primary,
        colorScheme: ColorScheme.fromSeed(seedColor: AppColors.primary),
        useMaterial3: true,
      ),
      home: const MainNavPage(),
    );
  }
}